Kit 4554 Introduce ruff (#12)
* KIT-4207 Handle network errors raised by "requests" in HttpTransport (#75)

* KIT-4207 Use context manager to manage sessions instead of handling it by ourself

* KIT-4207 Ensure that no log entries are written by the library during logger shutdown

* KIT-4207 Ensure that no log entries are written by the library during logger shutdown

* KIT-4207 Improve logging

* KIT-4207 Remove unused imports

* KIT-4207 Minor logging adjustments

* KIT-4207 Adjust unit tests

* KIT-4207 updated version in setup

* KIT-4207 updated version in setup

* KIT-4554 introduced ruff

* KIT-4554 removed pylint

* Bump version

---------

Co-authored-by: Stefan Rom <41320207+devRoemer@users.noreply.github.com>
Co-authored-by: aott <ottalexanderdev@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,14 +23,20 @@ jobs:
           python-version: "3.12"
       - name: Add linting matchers
         run: |
-          echo "::add-matcher::.github/flake8-error-problem-matcher.json"
-          echo "::add-matcher::.github/flake8-warning-problem-matcher.json"
-      - name: Lint
-        uses: py-actions/flake8@v2
+          echo "::add-matcher::.github/mypy-error-problem-matcher.json"
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements-dev.txt
+      - name: Create ruff failures dir
+        run: mkdir -p ./ruff_failures
+      - name: Lint with ruff
+        run: |
+          ruff check --output-format github . || echo "sag_py_auth" >> ./ruff_failures/ruff_failures.txt
+      - name: Lint typing
+        # Must run with installed dependencies
+        run: |
+          mypy --config-file .mypy.ini --show-column-numbers .
       - name: Run tests
         run: python -m pytest --cov=sag_py_logging_logstash --cov-report=xml tests
       - name: Prepare coverage file
